version: '3.9'

services:
  nodejs:
    container_name: nodejs_app
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres_app
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: firdavs2007
      POSTGRES_DB: product_typeorm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
